name: Deep Source

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  DeepSource:
    name: Deep Source Coverage report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install DeepSource scanner
        run: curl https://deepsource.io/cli | sh

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # - name: Test and coverage
      #   run: npm run test:coverage

      # - name: Build and analyze
      #   if: >-
      #     (
      #       github.event_name == 'push' &&
      #       github.ref == 'refs/heads/main'
      #     ) || (
      #       github.event_name == 'pull_request' &&
      #       github.event.pull_request.head.repo.full_name == github.repository
      #     ) || (
      #       github.event_name == 'workflow_dispatch'
      #     )
      #   env:
      #     DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
      #   run: ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/lcov.info
